name: example
description: A sample command-line application.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.2.5

dependencies:
  yandex_dictionary_api:
    path: ../

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
